- hosts: mysql_server
  become : true
  tasks :
    - name: Install mysql server
      dnf :
        name: mysql-server
        state: present
    - name: start and enable MySQL service
      systemd:
       name: mysqld
       state: started
       enabled: true
    - name: Secure MySQL installation
      systemd:
        name: mysqld
        state: started
        enabled: true

- hosts: backend_server
  become: true
  tasks:
    - name: Disable default NodeJs module
      dnf:
        name: nodejs
        state: absent
        disable_modular_filtering: true
        disablerepo: "*"
        enablerepo: "*"
    - name: Enable NodeJS 20 module
      dnf: 
        name: nodejs
        state: present
        enablerepo: "nodejs:20"
    - name: install nodejs
      dnf:
        name: nodejs
        state: present
    - name: add application user
      user:
        name: expense
        create_home: no
        system: yes
    - name: create application directory
      file: 
        path: /app
        state: directory
        owner: expense
        group: expense
    - name: download backend application
      get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    - name: extract backend application
      unarchive:
        src: /tmp/backend.zip
        dest: /app
        owner: expense
        group: expense
        remote_src: yes
    - name: install dependencies
      npm:
       path: /app
    - name: create backend service file
      copy:
        content: |
          [Unit]
          Description = Backend Service

          [Service]
          User=expense
          Environment=DB_HOST="172.31.80.117"
          ExecStart=/bin/node /app/index.js
          SyslogIdentifier=backend

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/backend.service
        owner: root
        group: root
    - name: Reload systemd daemon
      systemd:
        daemon_reload: true

    - name: Start and enable backend service
      systemd:
        name: backend
        state: started
        enabled: true

    - name: Install MySQL client
      dnf:
        name: mysql
        state: present

    - name: Load database schema
      command: "mysql -h 172.31.80.117 -uroot -pExpenseApp@1 < /app/schema/backend.sql"
      register: load_schema_output
      changed_when: "'Query OK' in load_schema_output.stdout"

    - name: Restart backend service
      systemd:
        name: backend
        state: restarted


- hosts: frontend_server
  become: true
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Remove default Nginx content
      file:
        path: /usr/share/nginx/html/*
        state: absent

    - name: Download frontend application
      get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: Extract frontend application
      unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Create Nginx reverse proxy configuration
      copy:
        content: |
          proxy_http_version 1.1;

          location /api/ { proxy_pass http://172.31.82.35:8080/; }

          location /health {
            stub_status on;
            access_log off;
          }
        dest: /etc/nginx/default.d/expense.conf
        owner: root
        group: root

    - name: Restart Nginx service
      systemd:
        name: nginx
        state: restarted
      