- name: data types
  hosts: localhost
  vars:
    Course: Ansible #string datatypes
    Tools: #list
      - Linux
      - Shell
      - Ansible
    Experience: # map or dictionary
      Devops: 3
      AWS: 2
      Docker: 1
    Project : true # boolean
  tasks:
   - name: printing variables
     ansible.builtin.debug:
      msg: "{{Course}},{{Tools}},{{Experience}},{{Project}}"
