- name: variable preference
  hosts: localhost
  # vars:
  #  name : sai from playlevel
  # vars_prompt:
  # - name: name
  #   prompt: enter your name
  #   private: false
  vars_files:
  - vars.yaml
  tasks:
  - name: check preference
    # vars:
    #  name: sai from tasklevel
    ansible.builtin.debug:
      msg: "{{name}}"
# 1. arguments
# 2. Task level
# 3. variable files
# 4. Prompt
# 5. Play level
# 6. inventory
# 7. role level