- name: check number 
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: Enter the number
    private: no
  tasks:
  - name: number is less than 100
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 100"
    when: number | int < 100
  - name: number is greater than 100
    ansible.builtin.debug:
      msg: "Given number {{number}} is greater than 100"
    when: number | int > 100