- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{item.name}}"
    loop:
    - {name:mysql,state:latest}
    - {name:nginx,state:absent}